from __future__ import annotations

from datetime import datetime, timezone

from .models import Conversation, Message


ROLE_LABELS = {
    "assistant": "Assistant",
    "user": "User",
    "source": "Source Transcript",
}


def render_conversation_note(
    conversation: Conversation,
    *,
    tags: list[str],
    synced_at: str | None = None,
) -> str:
    synced_at = synced_at or datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    title = conversation.title or "Untitled Conversation"

    parts = [
        "---",
        f"title: {_yaml_quote(title)}",
        f"source_file: {_yaml_quote(str(conversation.source_path))}",
        f"source_id: {_yaml_quote(conversation.source_id)}",
        f"created_at: {_yaml_quote(conversation.created_at or '')}",
        f"updated_at: {_yaml_quote(conversation.updated_at or '')}",
        f"synced_at: {_yaml_quote(synced_at)}",
        'status: "needs human review"',
        'type: "ai conversation"',
        'hub: "[[AI Conversation Index]]"',
        "tags:",
    ]
    parts.extend(f"  - {tag}" for tag in tags)
    parts.extend(
        [
            "---",
            "",
            f"# {title}",
            "",
            "[[AI Conversation Index|Back to AI Conversation Index]]",
            "",
            "> [!warning] Human review needed",
            "> This note was synced from a local conversation export. Review it before treating it as final documentation or sharing it publicly.",
            "",
            "## Human Summary",
            "",
            "- Status: needs review",
            "- Main takeaway: TODO",
            "- Why it matters: TODO",
            "",
            "## Connections",
            "",
            "- Project: [[Project - TODO]]",
            "- Learning log: [[Learning Log - TODO]]",
            "- Topic: #topic/TODO",
            "- Related note: [[Related Note - TODO]]",
            "",
            "## Useful Takeaways",
            "",
            "- TODO",
            "",
            "## Decisions, Commands, or Prompts",
            "",
            "- TODO",
            "",
            "## Follow-Up",
            "",
            "- [ ] Pull out reusable notes, commands, or decisions.",
            "- [ ] Link this note to a project, learning log, or topic page if useful.",
            "- [ ] Remove anything private before sharing publicly.",
            "",
            "## Conversation",
            "",
        ]
    )

    if conversation.messages:
        for message in conversation.messages:
            parts.append(_render_message(message))
    else:
        parts.append("_No readable messages were found in this source file._\n")

    return "\n".join(parts).rstrip() + "\n"


def render_index_note(
    entries: list[dict[str, str]],
    *,
    folder_title: str,
    synced_at: str | None = None,
) -> str:
    synced_at = synced_at or datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    sorted_entries = sorted(entries, key=lambda entry: entry.get("synced_at", ""), reverse=True)

    parts = [
        "---",
        'title: "AI Conversation Index"',
        'type: "index"',
        f"folder: {_yaml_quote(folder_title)}",
        f"updated_at: {_yaml_quote(synced_at)}",
        "tags:",
        "  - ai-conversation",
        "  - learning-notes",
        "  - documentation-workflow",
        "---",
        "",
        "# AI Conversation Index",
        "",
        "> [!info] Local sync hub",
        "> This index is generated by the Obsidian Conversation Sync Agent. Use it as an inbox for reviewing AI-assisted learning notes.",
        "",
        "## Review Queue",
        "",
    ]

    if sorted_entries:
        for entry in sorted_entries:
            link = _obsidian_link(entry.get("note_path", ""), entry.get("title", "Untitled Conversation"))
            source = entry.get("source_path", "unknown source")
            synced = entry.get("synced_at", "unknown sync time")
            parts.append(f"- {link} - needs review")
            parts.append(f"  - Source: `{source}`")
            parts.append(f"  - Synced: {synced}")
    else:
        parts.append("- No conversations synced yet.")

    parts.extend(
        [
            "",
            "## Review Workflow",
            "",
            "- [ ] Open a synced conversation note.",
            "- [ ] Fill in the human summary and useful takeaways.",
            "- [ ] Connect the note to a project, learning log, or topic.",
            "- [ ] Remove private details before anything becomes public documentation.",
            "",
            "## Common Hubs",
            "",
            "- [[Projects]]",
            "- [[Learning Journey]]",
            "- [[AI-Assisted Workflows]]",
            "- [[Documentation Practice]]",
        ]
    )

    return "\n".join(parts).rstrip() + "\n"


def _render_message(message: Message) -> str:
    label = ROLE_LABELS.get(message.role.lower(), message.role.title())
    created = f" ({message.created_at})" if message.created_at else ""
    return f"### {label}{created}\n\n{message.content.strip()}\n"


def _obsidian_link(path: str, title: str) -> str:
    note_path = path.replace("\\", "/")
    if note_path.endswith(".md"):
        note_path = note_path[:-3]
    safe_title = title.replace("[", "(").replace("]", ")").replace("|", "-")
    return f"[[{note_path}|{safe_title}]]"


def _yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
